version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: payment_method_laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"

    nginx:
        image: nginx:alpine
        container_name: payment_method_laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    postgres_data:
